title = "alexogeny"
description = "every freckled face needs its spectacles"
base_url = "https://alexogeny.dev"
theme = "alexogeny"
default_language = "en"
minify_html = true
taxonomies = [
  {name = "tags"}
]

[markdown]
highlight_code = true

[extra.social]
github = "alexogeny"
twitter = "alexogeny"

[extra.show]
tags = true

[languages.en.translations]
about = "About"
home = "Home"
tags = "Tags"
archive = "Archive"
links = "Links"
next_page = "Next Page"
previous_page = "Previous Page"
date_format = "%Y-%m-%d"
